/*
 * $class.javaName.java
 *
 * Generated by Protege plugin Beanynizer. 
 * This class implements the functionality of Incendio.
 * Feel free to change.
 *
 */
package disasters.caronte.ontology;

import disasters.Disaster;

/**
 * Editable Java class for concept <code>Incendio</code> of caronte ontology.
 */
public class Incendio extends IncendioData{
	//-------- constructors --------
	/**
	 * Default Constructor.<br>
	 * Create a new <code>Incendio</code>.
	 */
	public Incendio(){
		// Empty constructor required for JavaBeans (do not remove).
	}

	/**
	 * Clone Constructor.<br>
	 * Create a new <code>Incendio</code>.<br>
	 * Copy all attributes from <code>proto</code> to this instance.
	 *
	 * @param proto The prototype instance.
	 */
	public Incendio(Incendio proto){
		setDescripcion(proto.getDescripcion());
		setGravedad(proto.getGravedad());
		setId(proto.getId());
		setInfo(proto.getInfo());
		setNumHeridos(proto.getNumHeridos());
		setPosicion(proto.getPosicion());
	}

	//-------- custom code --------
	/**
	 *
	 * @param id
	 * @param descripcion
	 * @param info
	 * @param gravedad
	 * @param posicion
	 * @param numHeridos
	 */
	public Incendio(int id, String descripcion, String info, String gravedad, Posicion posicion, int numHeridos){
		setId(id);
		setDescripcion(descripcion);
		setInfo(info);
		setGravedad(gravedad);
		setPosicion(posicion);
		setNumHeridos(numHeridos);
	}
	
	/**
	 * 
	 * @param des 
	 * @param numHeridos 
	 */
	 public Incendio(Disaster des, int numHeridos){
		setId(des.getId());
		setDescripcion(des.getDescription());
		setInfo(des.getInfo());
		setGravedad(des.getSize());
		setPosicion(new Posicion(new Float(des.getLatitud()), new Float(des.getLongitud()), des.getFloor()));
		setNumHeridos(numHeridos);
	}

	//-------- Object methods -----
	/**
	 * Get a string representation of this <code>Incendio</code>.
	 *
	 * @return The string representation.
	 */
	public String toString(){
		return "Incendio(id=" + getId() + ", descripcion=" + getDescripcion() + ", info=" + getInfo() +
			", gravedad=" + getGravedad() + ", posicion=" + getPosicion() + ", numHeridos=" + getNumHeridos() + ")";
	}

	/**
	 * Get a clone of this <code>Incendio</code>.
	 *
	 * @return a shalow copy of this instance.
	 */
	public Object clone(){
		return new Incendio(this);
	}

	/**
	 * Test the equality of this <code>Incendio</code> and an object <code>obj</code>.
	 *
	 * @param obj the object this test will be performed with
	 * @return false if <code>obj</code> is not of <code>Incendio</code> class,
	 *         true if all attributes are equal.
	 */
	public boolean equals(Object obj){
		if(obj instanceof Incendio){
			Incendio cmp = (Incendio) obj;
			if(getDescripcion() != cmp.getDescripcion() &&
					(getDescripcion() == null || !getDescripcion().equals(cmp.getDescripcion()))){
				return false;
			}
			if(getGravedad() != cmp.getGravedad() &&
					(getGravedad() == null || !getGravedad().equals(cmp.getGravedad()))){
				return false;
			}
			if(getId() != cmp.getId()){
				return false;
			}
			if(getInfo() != cmp.getInfo() &&
					(getInfo() == null || !getInfo().equals(cmp.getInfo()))){
				return false;
			}
			if(getNumHeridos() != cmp.getNumHeridos()){
				return false;
			}
			if(getPosicion() != cmp.getPosicion() &&
					(getPosicion() == null || !getPosicion().equals(cmp.getPosicion()))){
				return false;
			}
			return true;
		}
		return false;
	}
}