/*
 * Persona.java
 *
 * Generated by Protege plugin Beanynizer. 
 * This class implements the functionality of Persona.
 * Feel free to change.
 *
 */
package disasters.caronte.ontology;

import disasters.Resource;

/**
 * Editable Java class for concept <code>Persona</code> of caronte ontology.
 */
public class Persona extends PersonaData{
	//-------- constructors --------
	/**
	 * Default Constructor.</br>
	 * Create a new <code>Persona</code>.
	 */
	public Persona(){
		// Empty constructor required for JavaBeans (do not remove).
	}

	/**
	 * Clone Constructor.</br>
	 * Create a new <code>Persona</code>.</br>
	 * Copy all attributes from <code>proto</code> to this instance.
	 *
	 * @param proto the prototype instance
	 */
	public Persona(Persona proto){
		setId(proto.getId());
		setTipo(proto.getTipo());
	}

	//-------- custom code --------
	/**
	 * Create a new <code>Persona</code>.
	 * 
	 * @param id identificador
	 * @param tipo tipo
	 */
	public Persona(int id, String tipo){
		setId(id);
		setTipo(tipo);
	}
	
	/**
	 * Create a new <code>Persona</code>.
	 * 
	 * @param per persona
	 */
	public Persona(Resource per){
		setId(per.getId());
		setTipo(per.getType());
	}
	
	//-------- Object methods -----
	/**
	 * Get a string representation of this <code>Persona</code>.
	 *
	 * @return The string representation.
	 */
	public String toString(){
		return "Persona(id=" + getId() + ", tipo=" + getTipo() + ")";
	}

	/**
	 * Get a clone of this <code>Persona</code>.
	 *
	 * @return a shalow copy of this instance
	 */
	public Object clone(){
		return new Persona(this);
	}

	/**
	 * Test the equality of this <code>Persona</code> and an object <code>obj</code>.
	 *
	 * @param obj the object this test will be performed with
	 * @return <code>false</code> if <code>obj</code> is not of <code>Persona</code> class,
	 *         <code>true</code> if all attributes are equal
	 */
	public boolean equals(Object obj){
		if(obj instanceof Persona){
			Persona cmp = (Persona) obj;
			if(getId() != cmp.getId()){
				return false;
			}
			if(getTipo() != cmp.getTipo() && (getTipo() == null || !getTipo().equals(cmp.getTipo()))){
				return false;
			}
			return true;
		}
		return false;
	}
}