/*
 * PersonaData.java
 *
 * Generated by Protege plugin Beanynizer. 
 * Changes will be lost! 
 */
package disasters.caronte.ontology;



/**
 *  Java class for concept Persona of caronte ontology.
 */
public abstract class PersonaData implements java.beans.BeanInfo 
{
	//-------- constants ----------

	//-------- attributes ----------

	/** Attribute for slot id. */
	protected  int  id;

	/** Attribute for slot tipo. */
	protected  String  tipo;

	//-------- constructors --------

	/**
	 *  Default Constructor. <br>
	 *  Create a new <code>Persona</code>.
	 */
	public PersonaData()  {
	}

	//-------- accessor methods --------

	/**
	 *  Get the id of this Persona.
	 * @return id
	 */
	public int  getId() {
		return this.id;
	}

	/**
	 *  Set the id of this Persona.
	 * @param id the value to be set
	 */
	public void  setId(int id) {
		this.id = id;
	}

	/**
	 *  Get the tipo of this Persona.
	 * @return tipo
	 */
	public String  getTipo() {
		return this.tipo;
	}

	/**
	 *  Set the tipo of this Persona.
	 * @param tipo the value to be set
	 */
	public void  setTipo(String tipo) {
		this.tipo = tipo;
	}

	//-------- bean related methods --------

	/** The property descriptors, constructed on first access. */
	private java.beans.PropertyDescriptor[] pds = null;

	/**
	 *  Get the bean descriptor.
	 *  @return The bean descriptor.
	 */
	public java.beans.BeanDescriptor getBeanDescriptor() {
		return null;
	}

	/**
	 *  Get the property descriptors.
	 *  @return The property descriptors.
	 */
	public java.beans.PropertyDescriptor[] getPropertyDescriptors() {
		if(pds==null) {
			try {
				pds = new java.beans.PropertyDescriptor[]{
					 new java.beans.PropertyDescriptor("id", this.getClass(), "getId", "setId")
					, new java.beans.PropertyDescriptor("tipo", this.getClass(), "getTipo", "setTipo")
				};
			}
			catch(Exception e) {
				e.printStackTrace();
			}
		}
		return pds;
	}

	/**
	 *  Get the default property index.
	 *  @return The property index.
	 */
	public int getDefaultPropertyIndex() {
		return -1;
	}

	/**
	 *  Get the event set descriptors.
	 *  @return The event set descriptors.
	 */
	public java.beans.EventSetDescriptor[] getEventSetDescriptors() {
		return null;
	}

	/**
	 *  Get the default event index.
	 *  @return The default event index.
	 */
	public int getDefaultEventIndex() {
		return -1;
	}

	/**
	 *  Get the method descriptors.
	 *  @return The method descriptors.
	 */
	public java.beans.MethodDescriptor[] getMethodDescriptors() {
		return null;
	}

	/**
	 *  Get additional bean info.
	 *  @return Get additional bean info.
	 */
	public java.beans.BeanInfo[] getAdditionalBeanInfo() {
		return null;
	}

	/**
	 *  Get the icon.
	 *  @return The icon.
	 */
	public java.awt.Image getIcon(int iconKind) {
		return null;
	}

	/**
	 *  Load the image.
	 *  @return The image.
	 */
	public java.awt.Image loadImage(final String resourceName) {
		try {
			final Class c = getClass();
			java.awt.image.ImageProducer ip = (java.awt.image.ImageProducer)
				java.security.AccessController.doPrivileged(new java.security.PrivilegedAction() {
					public Object run(){
						java.net.URL url;
						if((url = c.getResource(resourceName))==null) {
							return null;
						}
						else {
							try {
								return url.getContent();
							}
							catch(java.io.IOException ioe) {
								return null;
							}
						}
					}
				});
			if(ip==null)
				return null;
			java.awt.Toolkit tk = java.awt.Toolkit.getDefaultToolkit();
			return tk.createImage(ip);
		}
		catch(Exception ex) {
			return null;
		}
	}

	//-------- additional methods --------

	/**
	 *  Get a string representation of this Persona.
	 *  @return The string representation.
	 */
	public String toString() {
		return "Persona("
           + ")";
	}

}
