/*
 * $class.javaName.java
 *
 * Generated by Protege plugin Beanynizer. 
 * This class implements the functionality of Posicion.
 * Feel free to change.
 *
 */
package disasters.caronte.ontology;

import disasters.Position;

/**
 * Editable Java class for concept <code>Posicion</code> of caronte ontology.
 */
public class Posicion extends PosicionData{
	//-------- constructors --------
	/**
	 * Default Constructor.<br>
	 * Create a new <code>Posicion</code>.
	 */
	public Posicion(){
		// Empty constructor required for JavaBeans (do not remove).
	}

	/**
	 * Clone Constructor.<br>
	 * Create a new <code>Posicion</code>.<br>
	 * Copy all attributes from <code>proto</code> to this instance.
	 *
	 * @param proto The prototype instance.
	 */
	public Posicion(Posicion proto){
		setLatitud(proto.getLatitud());
		setLongitud(proto.getLongitud());
		setPlanta(proto.getPlanta());
	}

	//-------- custom code --------
	/**
	 *
	 * @param latitud
	 * @param longitud
	 * @param planta
	 */
	public Posicion(float latitud, float longitud, int planta){
		setLatitud(latitud);
		setLongitud(longitud);
		setPlanta(planta);
	}

	/**
	 *
	 * @param pos
	 * @param planta
	 */
	public Posicion(Position pos, int planta){
		setLatitud(pos.getLat());
		setLongitud(pos.getLng());
		setPlanta(planta);
	}

	//-------- Object methods -----
	/**
	 * Get a string representation of this <code>Posicion</code>.
	 *
	 * @return The string representation.
	 */
	public String toString(){
		return "Posicion(latitud=" + getLatitud() + ", longitud="  + getLongitud() + ", planta=" + getPlanta() + ")";
	}

	/**
	 * Get a clone of this <code>Posicion</code>.
	 *
	 * @return a shalow copy of this instance.
	 */
	public Object clone(){
		return new Posicion(this);
	}

	/**
	 * Test the equality of this <code>Posicion</code> and an object <code>obj</code>.
	 *
	 * @param obj the object this test will be performed with
	 * @return false if <code>obj</code> is not of <code>Posicion</code> class,
	 *         true if all attributes are equal.
	 */
	public boolean equals(Object obj){
		if(obj instanceof Posicion){
			Posicion cmp = (Posicion) obj;
			if(getLatitud() != cmp.getLatitud()){
				return false;
			}
			if(getLongitud() != cmp.getLongitud()){
				return false;
			}
			if(getPlanta() != cmp.getPlanta()){
				return false;
			}
			return true;
		}
		return false;
	}
}