/*
 * DesastreData.java
 *
 * Generated by Protege plugin Beanynizer. 
 * Changes will be lost! 
 */
package jadex.desastres;

import jadex.commons.SReflect;



/**
 *  Java class for concept Desastre of caronte ontology.
 */
public abstract class DesastreData{
	//-------- constants ----------

	//-------- attributes ----------

	/** Attribute for slot estado_heridos. */
	protected  String  estadoheridos;

	/** Attribute for slot estado_emergencia. */
	protected  String  estadoemergencia;

	/** Attribute for slot id. */
	protected  int  id;

	//-------- constructors --------

	/**
	 *  Default Constructor. <br>
	 *  Create a new <code>Desastre</code>.
	 */
	public DesastreData()  { //
	}

	//-------- accessor methods --------

	/**
	 *  Get the estado_heridos of this Desastre.
	 * @return estado_heridos
	 */
	public String  getEstadoHeridos() {
		return this.estadoheridos;
	}

	/**
	 *  Set the estado_heridos of this Desastre.
	 * @param estadoheridos the value to be set
	 */
	public void  setEstadoHeridos(String estadoheridos) {
		this.estadoheridos = estadoheridos;
	}

	/**
	 *  Get the estado_emergencia of this Desastre.
	 * @return estado_emergencia
	 */
	public String  getEstadoEmergencia() {
		return this.estadoemergencia;
	}

	/**
	 *  Set the estado_emergencia of this Desastre.
	 * @param estadoemergencia the value to be set
	 */
	public void  setEstadoEmergencia(String estadoemergencia) {
		this.estadoemergencia = estadoemergencia;
	}

	/**
	 *  Get the id of this Desastre.
	 * @return id
	 */
	public int  getId() {
		return this.id;
	}

	/**
	 *  Set the id of this Desastre.
	 * @param id the value to be set
	 */
	public void  setId(int id) {
		this.id = id;
	}

	//-------- object methods --------

	/**
	 *  Get a string representation of this Desastre.
	 *  @return The string representation.
	 */
	public String toString() {
		//return "Desastre("
				//+ ")";
		return SReflect.getInnerClassName(getClass())+
				" id="+getId()+", estadoemergencia="+getEstadoEmergencia()+", heridos="+getEstadoHeridos();
	}
	
	//--------- nuggets methods ---------
	
	/**
	 * Persist this Desastre using the nuggets utility.
	 * @param c 
	 */
	/*public void _persist(nuggets.ICruncher c) {
		// declare references
		// persist the nugget
		c.startConcept(this);
		if (estadoemergencia!=null) 
			c.put("estadoemergencia", estadoemergencia);
		if (estadoheridos!=null) 
			c.put("estadoheridos", estadoheridos);
		if (id!=0) 
			c.put("id", String.valueOf(id));
	}*/
	
	/**
	 * Restore this Desastre 
	 * @param a the name of the attribute
	 * @param v the value of the attribute
	 */
	/*public void _set(String a, Object v) { //
		switch(hash(a)) {
		case 0: id =  Integer.parseInt((String)v); return;
		case 1: estadoheridos =  (String)v; return;
		case 2: estadoemergencia =  (String)v; return;
		}                        
	}*/
	
/*private static final int hash(String name) {
  int h=0;
  int c=name.length();
   if (c<=6) return 0;
   h += 457258015*name.charAt(6);
   return (h>>>15)%3;
}*/

}
