package disasters.otros;

import disasters.Disaster;
import disasters.desastres.Environment;
import jadex.bdi.runtime.Plan;
import java.net.*;
import java.io.*;

/**
 *
 * @author luis
 */
public class HarmPlan extends Plan{

    Environment env;
    double spreading = 0.02;

    public void body(){
        System.out.println("$$ apocalypse-HarmPlan: start");
        env = (Environment) getBeliefbase().getBelief("env").getFact();
        Disaster dis = (Disaster) getBeliefbase().getBelief("unattendedDisaster").getFact();
        //firstly we fetch the position of this fire, so that we can create a new one close to it
        double latitud = dis.getLatitud() + Math.random() * spreading - spreading / 2;
        double longitud = dis.getLongitud() + Math.random() * spreading - spreading / 2;
        //create the new fire event in the database        
        String request = Environment.URL + "post/type=" + dis.getType() + "&name=" + dis.getName() + "X&quantity=1&latitud=" + latitud + "&longitud=" + longitud + "&size=" + dis.getSize() + "&traffic=" + dis.getTraffic();
        sendToDB(request);
        System.out.println("$$ apocalypse-HarmPlan: end");
    }

    /**
     * This method works as an communication interface to the database. It sends
     * the given String as an URL and saves the response generated by the database.
     * @param st - The String to send to the database
     * @return the response returned by the database
     */
    public static String sendToDB(String st){
        String response = new String();
        try{
            URL url = new URL(st);
            URLConnection workingConnection = url.openConnection();
            String inputLine;
            StringBuffer buff = new StringBuffer();
            BufferedReader dis = new BufferedReader(new InputStreamReader(workingConnection.getInputStream()));
            while ((inputLine = dis.readLine()) != null){
                buff.append(inputLine);
            }
            response = buff.toString();
            dis.close();
        }catch (MalformedURLException me){
            System.out.println("MalformedURLException: " + me);
        }catch (IOException ioe){
            System.out.println("IOException: " + ioe);
        }
        return response;
    }
}